### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by trotzig**
This PR bumps dependencies and replaces `request` with `node-fetch` (the former is no longer maintained).  Also drops Node 10 support.

### CODE REVIEW

**Comment by ljharb** [comment]
I'd be very careful using node-fetch; the latest version drops CJS support - I'd suggest avoiding any package authors that do things that are user-hostile like that.

**Comment by trotzig** [comment]
@ljharb Glad someone feels that way about dropping cjs (I'm annoyed too...). Do you have any good alternatives to node-fetch? It feels like a step in the right direction to move to the fetch standard at least.

**Comment by ljharb** [comment]
fetch isn't a standard outside of browsers, and it's impossible to have a standards-compliant one in node.

axios seems like a good bet?

**Comment by trotzig** [comment]
I appreciate the feedback. I won't spend the effort to switch right now but I'll keep it in mind for the future.

**Pull request merged**
