### PR TITLE
Improve finding the root node

### LINKED ISSUE #95: Blank screenshots for components that are mostly rendered in portals
We have a component that renders everything inside a portal (created by using react-dom's `createPortal`). The screenshots for this component are always blank. Looking at the source in the happo report and most of the DOM nodes for these examples are missing.

I dug through the code, and I believe that our problem lies in this code: https://github.com/happo/happo.io/blob/2ff1257f757d1d5f8ba0f5bdff4a3c44d780fdeb/src/browser/processor.js#L12-L32

It looks like happo has some logic to account for examples that are rendered entirely inside a portal (checks to see if the root element is completely empty), however in our case there is some content that is rendered in the root element (a div or two, but with no styling) and most of the interesting bits are inside the portal.

### PR DESCRIPTION
**Pull request by trotzig**
Fixes #95.

Before, when an example renders to multiple DOM nodes, we would just
include one of them in the html snapshot. In many cases, this led to
empty/blank screenshots. Consider this html:

```html
<body>
  <div id="happo-root"><div></div></div>
  <div>
    I'm in a portal!
  </div>
</body>
```

With the old findRoot() implementation, only the inner div of
`#happo-root` would be included in the html snapshot. With the new
implementation, both elements would be included:

```html
<div id="happo-root"><div></div></div>
<div>
  I'm in a portal!
</div>
</html>

This change is a little delicate as we have to be careful about
including too much in the html snapshot. For instance, if a React
component only renders to a portal, we don't want to include the empty
root:

this
```html
<body>
  <div id="happo-root"></div>
  <div>
    I'm in a portal!
  </div>
</body>
```

should result in
```html
<div>
  I'm in a portal!
</div>
```

Why is this important? Because we want to keep screenshots as small as
possible, and by including outer divs we (usually) end up with page-wide
screenshots. If we have the portal render in a narrow container, the
empty `#happo-root` div would cause the screenshot to be full-width.

this
```
<body>
  <div id="happo-root"></div>
  <div style="width: 100px">
    I'm in a portal!
  </div>
</body>
```

should produce a screenshot that is 100px wide. If we were to include
`#happo-root` here, the screenshot would be as wide as the viewport is
(unless there's some css preventing default div styling to apply to
`#happo-root`).

### CODE REVIEW

**Comment by trotzig** [comment]
If you're looking to try out this new behavior, version `3.22.0-rc.1` was just released with support for it.

```bash
npm install --save-dev happo.io@3.22.0-rc.1
```
or
```bash
npm install --save-dev happo.io@next
```

**Comment by lencioni** [comment]
This looks pretty good. I think it could miss some things, like single nodes in portals with no content but are styled in an important way, but maybe that's okay? Perhaps if that comes up, there can be an option on the specific example to make it work?

**Comment by trotzig** [comment]
@lencioni I tried to have that case covered as well. Or perhaps I'm misunderstanding something? This portal should still work: 

```js
export const innerPortal = () => (
  <React.Fragment>
    <main />
    <PortalComponent>
      Inside portal
    </PortalComponent>
  </React.Fragment>
);
```
The resulting html should look something like this: 
```html
<main />
<div>Inside portal</div>
```

**Comment by lencioni** [comment]
I was thinking if you had a portal that was a single DOM node and no contents. Something like:

```js
createPortal(<div style={{ border: '1px solid red', height: 10 }} />, document.body);
```

**Pull request merged**
