### PR TITLE
Replace jsonwebtoken with jose

### PR DESCRIPTION
**Pull request by lencioni**
We received a report of this package failing with the following error:

> TypeError: Right-hand side of 'instanceof' is not an object

The stack trace pointed at the jsonwebtoken package as the source.

At first it looked like this may be a problem on older versions of Node, but it turned out that they were using a relatively recent version (v18.17.1).

It appears that a lot of other people may be running into a similar issue:

- https://github.com/auth0/node-jsonwebtoken/issues/939
- https://github.com/auth0/node-jsonwebtoken/issues/892

People have reported success by either downgrading jsonwebtoken to v8 or replacing it with jose. Since we updated to jsonwebtoken v9 to fix a security vulnerability, I don't think it is a great idea to go back to v8.

jose seems to be well-supported, healthy, and active:

https://snyk.io/advisor/npm-package/jose

Let's give this a shot!

The API is a little bit different than jsonwebtoken, but for the most part I think the new version is simple enough to transition to. I set the alg properity to HS256, since it is required to specify the alg and that is what jsonwebtoken uses as the default.

It seems that jose uses `||=` syntax which is not supported on node 14, so I am also removing the node 14 tests as part of this commit. I'll look into adding node 20 and 22 to the test matrix in a followup.

### CODE REVIEW

**Comment by trotzig** [comment]
Seems like a pragmatic approach even though it would be good to get to the bottom of why so many fail to run with jsonwebtoken@9 (I suspect polyfills for `crypto`). 

Feel free to ditch node 14 from the matrix, and then release as a major release.

**Review by trotzig — APPROVED** [review]

**Comment by lencioni** [comment]
@trotzig I noticed that the tests failed on node 14 due to jose using some syntax that is not supported until node 16. To address this I decided to stop running the tests on node 14 (and added 20 and 22 while I was at it). What do you think about that?

**Comment by lencioni** [comment]
Looks like node 20 and 22 tests aren't working out (https://github.com/happo/happo.io/actions/runs/9571942826/job/26390148668?pr=276), so I'll be looking to add those to the test matrix in a follow up. I think one of the error messages we are asserting against is a little different for some reason.

**Comment by trotzig** [comment]
It looks like we just have to update the assertion?

**Pull request merged**
